{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.agentmirror.core",
    "module": "core-terminal",
    "version": "20260915.agent",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-terminal-20260915.agent.jar",
          "url": "core-terminal-20260915.agent.jar",
          "size": 59036,
          "sha512": "d33a8fc436c4b51046c402838ab1b7a7cf3e15ee9e25a7199454d9992370643da3d6677b8c40a6352ab49eb09863d74fdd1cb85261c2d588c341c2096da5c245",
          "sha256": "d2db2ab4d82654b3512205f4c8623bd49017465286c488e13ce9ef200e235d97",
          "sha1": "5491fc681c660209ee63bc014c56945118a35f06",
          "md5": "2736483705e272027590d009fa7c5d76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-terminal-20260915.agent.jar",
          "url": "core-terminal-20260915.agent.jar",
          "size": 59036,
          "sha512": "d33a8fc436c4b51046c402838ab1b7a7cf3e15ee9e25a7199454d9992370643da3d6677b8c40a6352ab49eb09863d74fdd1cb85261c2d588c341c2096da5c245",
          "sha256": "d2db2ab4d82654b3512205f4c8623bd49017465286c488e13ce9ef200e235d97",
          "sha1": "5491fc681c660209ee63bc014c56945118a35f06",
          "md5": "2736483705e272027590d009fa7c5d76"
        }
      ]
    }
  ]
}
