{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.agentmirror.core",
    "module": "core-conn",
    "version": "20260914.032773d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.agentmirror.core",
          "module": "core-protocol",
          "version": {
            "requires": "20260914.032773d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-conn-20260914.032773d.jar",
          "url": "core-conn-20260914.032773d.jar",
          "size": 47192,
          "sha512": "9b057a9589170a45b5374fe01264c2c3b85112f6d8231e9b8c6f29470b2d4d7505d517603a14b1d4fa256421f2d9a15bd698b939a4ae266abea8958952b02227",
          "sha256": "d245fe1571e4ee87b61ab8bee238426f72305ed5002507c45138454486a03153",
          "sha1": "297da72ce83588e3035f0d9aa7b087e9324e7268",
          "md5": "b15736b26d53f3c1800a1f768b7a3204"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.agentmirror.core",
          "module": "core-protocol",
          "version": {
            "requires": "20260914.032773d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-conn-20260914.032773d.jar",
          "url": "core-conn-20260914.032773d.jar",
          "size": 47192,
          "sha512": "9b057a9589170a45b5374fe01264c2c3b85112f6d8231e9b8c6f29470b2d4d7505d517603a14b1d4fa256421f2d9a15bd698b939a4ae266abea8958952b02227",
          "sha256": "d245fe1571e4ee87b61ab8bee238426f72305ed5002507c45138454486a03153",
          "sha1": "297da72ce83588e3035f0d9aa7b087e9324e7268",
          "md5": "b15736b26d53f3c1800a1f768b7a3204"
        }
      ]
    }
  ]
}
