from ledgerdsl import WT, Check, EnvironmentFidelity, FallbackDef, Handoff, InlineScript, Ledger, Provenance, Resources, ScriptRef, Task, dep, role

base = dict(environment_fidelity=EnvironmentFidelity(runs_real_cli=True), provenance=Provenance(identity="git", revision="6625b2c25190db8e042aa347be0606c1a85b81f8"))
roles = {
 "test": role(".team/nodes/emu-own-test/", agent="sampler-test-luna2", team="remote-agent-android", provider="codex"),
 "probe": role(".team/nodes/emu-own-probe/", agent="sampler-review-luna2", team="remote-agent-android", provider="codex"),
 "impl": role(".team/nodes/emu-own/", agent="sampler-dev-luna2", team="remote-agent-android", provider="codex"),
 "verify": role(".team/nodes/emu-own-verify/", agent="sampler-review-luna2", team="remote-agent-android", provider="codex"),
 "advisor": role(".team/nodes/input-full-auto/advisor/", agent="input-advisor-luna", team="remote-agent-android", provider="codex"),
}
test_check = InlineScript(text="f=.team/nodes/emu-own-test/RED.md\n[ -e \"$f\" ] || exit 1\n[ -r \"$f\" ] || exit 2\n[ -s \"$f\" ] || exit 1\ncommand -v grep >/dev/null 2>&1 || exit 2\ngrep -F fullpath_qemu_bound \"$f\" >/dev/null || exit 1\ngrep -F zero_count_exit \"$f\" >/dev/null || exit 1\ngrep -F zero_count_no_orphan \"$f\" >/dev/null || exit 1\n")
probe_check = InlineScript(text="f=.team/nodes/emu-own-probe/PROBE.md\n[ -e \"$f\" ] || exit 1\n[ -r \"$f\" ] || exit 2\n[ -s \"$f\" ] || exit 1\ncommand -v grep >/dev/null 2>&1 || exit 2\ngrep -F qemu-system \"$f\" >/dev/null || exit 1\ngrep -F basename \"$f\" >/dev/null || exit 1\ngrep -F measurement \"$f\" >/dev/null || exit 1\ngrep -F only_owned_pid \"$f\" >/dev/null || exit 1\n")
test = Task(title="按 `.team/nodes/spec-sol/emu-own/任务书.md` 并行产出模拟器所有权场景红测审计；只写 RED.md，须覆盖 fullpath_qemu_bound、zero_count_exit、zero_count_no_orphan，齐后 report_result。", owner_role="test", seat_wait_seconds=1800, parallel="emu-own-wave", resources=Resources(worktree_id="wt-emu-own-test", write_paths=[".team/nodes/emu-own-test/"], read_paths=[".team/nodes/spec-sol/emu-own/任务书.md", ".team/nodes/spec-sol/envcheck-emu/任务书.md", ".team/ledgers/acceptance/emu-own.sh", "tools/perfbase/run-input-ab.sh", "tools/perfbase/envcheck.sh"], **base), handoff=Handoff(required_artifacts=[".team/nodes/emu-own-test/RED.md"]), checks=[Check(id="M.emu-own.test", script=test_check, cwd=WT, expected=0, unjudgeable=[2], budget=120)])
probe = Task(title="按 `.team/nodes/spec-sol/emu-own/任务书.md` 并行产出 qemu PID/adb serial 绑定与清理根因探针；只写 PROBE.md，须覆盖 qemu-system、basename、measurement、only_owned_pid，齐后 report_result。", owner_role="probe", seat_wait_seconds=1800, parallel="emu-own-wave", resources=Resources(worktree_id="wt-emu-own-probe", write_paths=[".team/nodes/emu-own-probe/"], read_paths=[".team/nodes/spec-sol/emu-own/任务书.md", ".team/nodes/spec-sol/envcheck-emu/任务书.md", ".team/ledgers/acceptance/emu-own.sh", "tools/perfbase/run-input-ab.sh", "tools/perfbase/envcheck.sh"], **base), handoff=Handoff(required_artifacts=[".team/nodes/emu-own-probe/PROBE.md"]), checks=[Check(id="M.emu-own.probe", script=probe_check, cwd=WT, expected=0, unjudgeable=[2], budget=120)])
impl = Task(title="按 `.team/nodes/spec-sol/emu-own/任务书.md` 并行实现 runner 启动、唯一 qemu PID 与 adb serial 绑定、失败清理/恢复及聚焦测试；只改任务书列明路径，齐后 report_result。", owner_role="impl", seat_wait_seconds=3600, parallel="emu-own-wave", resources=Resources(worktree_id="wt-emu-own-impl", write_paths=["tools/perfbase/run-input-ab.sh", "tools/perfbase/envcheck.sh", "tools/perfbase/test-run-input-ab-emulator-ownership.sh", ".team/nodes/emu-own/"], read_paths=[".team/nodes/spec-sol/emu-own/任务书.md", ".team/nodes/spec-sol/envcheck-emu/任务书.md", ".team/ledgers/acceptance/emu-own.sh", ".team/ledgers/acceptance/envcheck-emu.sh", "CLAUDE.md", "tools/perfbase/"], **base), handoff=Handoff(required_artifacts=[".team/nodes/emu-own/IMPL.md"]), checks=[Check(id="M.emu-own.impl", script=ScriptRef(path=".team/ledgers/acceptance/emu-own.sh", expect=0, unjudgeable=[2]), cwd=WT, budget=600)])
verify = Task(title="按 `.team/nodes/spec-sol/emu-own/任务书.md` 独立终审 wt-emu-own-impl；重跑机械门并选择 comm 归一或 PID 绑定破坏齿，齐后 report_result。", owner_role="verify", seat_wait_seconds=1800, resources=Resources(worktree_id="wt-emu-own-impl", write_paths=[".team/nodes/emu-own-verify/"], read_paths=[".team/nodes/spec-sol/emu-own/任务书.md", ".team/nodes/emu-own-test/", ".team/nodes/emu-own-probe/", ".team/ledgers/acceptance/emu-own.sh", ".team/ledgers/acceptance/envcheck-emu.sh", "tools/perfbase/"], **base), handoff=Handoff(required_artifacts=[".team/nodes/emu-own-verify/VERDICT.md"]), checks=[Check(id="M.emu-own.verify", script=ScriptRef(path=".team/ledgers/acceptance/emu-own.sh", expect=0, unjudgeable=[2]), cwd=WT, budget=600)])
ledger = Ledger(ledger_id="ledger.emu-own.v1", roles=roles, tasks={"t.emu-own.test":test,"t.emu-own.probe":probe,"t.emu-own.impl":impl,"t.emu-own.verify":verify}, dependencies=[dep("t.emu-own.test","t.emu-own.verify"),dep("t.emu-own.probe","t.emu-own.verify"),dep("t.emu-own.impl","t.emu-own.verify")], parallelism=[{"group":"emu-own-wave","max_concurrency":3,"failure_policy":"halt"}], fallback={"F.escalate":FallbackDef(role="advisor",triggers=["blocked_on_unknown","provider_unavailable","result_deadline_elapsed","delivery_uncertain"])}, repo_root="/Volumes/nvme/Projects/远程Agent安卓")
print(ledger.compile(), end="")
