from ledgerdsl import WT, Check, EnvironmentFidelity, FallbackDef, Handoff, InlineScript, Ledger, Provenance, Resources, ScriptRef, Task, dep, role

base = dict(environment_fidelity=EnvironmentFidelity(runs_real_cli=True), provenance=Provenance(identity="git", revision="3029dfae6b0adb40e01b7e9052bf3a02f9d2d32c"))
roles = {
 "test": role(".team/nodes/envcheck-emu-test/", agent="sampler-test-luna2", team="remote-agent-android", provider="codex"),
 "probe": role(".team/nodes/envcheck-emu-probe/", agent="sampler-review-luna2", team="remote-agent-android", provider="codex"),
 "impl": role(".team/nodes/envcheck-emu/", agent="sampler-dev-luna2", team="remote-agent-android", provider="codex"),
 "verify": role(".team/nodes/envcheck-emu-verify/", agent="sampler-review-luna2", team="remote-agent-android", provider="codex"),
 "advisor": role(".team/nodes/input-full-auto/advisor/", agent="input-advisor-luna", team="remote-agent-android", provider="codex"),
}
test_check = InlineScript(text="f=.team/nodes/envcheck-emu-test/RED.md\n[ -e \"$f\" ] || exit 1\n[ -r \"$f\" ] || exit 2\n[ -s \"$f\" ] || exit 1\ncommand -v grep >/dev/null 2>&1 || exit 2\ngrep -F owned_high_load \"$f\" >/dev/null || exit 1\ngrep -F extra_qemu \"$f\" >/dev/null || exit 1\ngrep -F cleanup_signal \"$f\" >/dev/null || exit 1\n")
probe_check = InlineScript(text="f=.team/nodes/envcheck-emu-probe/PROBE.md\n[ -e \"$f\" ] || exit 1\n[ -r \"$f\" ] || exit 2\n[ -s \"$f\" ] || exit 1\ncommand -v grep >/dev/null 2>&1 || exit 2\ngrep -F qemu-system \"$f\" >/dev/null || exit 1\ngrep -F adb \"$f\" >/dev/null || exit 1\ngrep -F trap \"$f\" >/dev/null || exit 1\ngrep -F MAX_LOAD=12 \"$f\" >/dev/null || exit 1\n")
test = Task(title="按 `.team/nodes/spec-sol/envcheck-emu/任务书.md` 并行产出八臂场景红测审计；只写 RED.md，须覆盖 owned_high_load、extra_qemu、cleanup_signal，齐后 report_result。", owner_role="test", seat_wait_seconds=1800, parallel="envcheck-emu-wave", resources=Resources(worktree_id="wt-envcheck-test", write_paths=[".team/nodes/envcheck-emu-test/"], read_paths=[".team/nodes/spec-sol/envcheck-emu/任务书.md", ".team/ledgers/acceptance/envcheck-emu.sh", "tools/perfbase/envcheck.sh", "tools/perfbase/run-input-ab.sh"], **base), handoff=Handoff(required_artifacts=[".team/nodes/envcheck-emu-test/RED.md"]), checks=[Check(id="M.envcheck-emu.test", script=test_check, cwd=WT, expected=0, unjudgeable=[2], budget=120)])
probe = Task(title="按 `.team/nodes/spec-sol/envcheck-emu/任务书.md` 并行产出所有权/清理根因探针；只写 PROBE.md，须覆盖 qemu-system PID、adb、trap、MAX_LOAD=12，齐后 report_result。", owner_role="probe", seat_wait_seconds=1800, parallel="envcheck-emu-wave", resources=Resources(worktree_id="wt-envcheck-probe", write_paths=[".team/nodes/envcheck-emu-probe/"], read_paths=[".team/nodes/spec-sol/envcheck-emu/任务书.md", ".team/ledgers/acceptance/envcheck-emu.sh", "tools/perfbase/envcheck.sh", "tools/perfbase/run-input-ab.sh"], **base), handoff=Handoff(required_artifacts=[".team/nodes/envcheck-emu-probe/PROBE.md"]), checks=[Check(id="M.envcheck-emu.probe", script=probe_check, cwd=WT, expected=0, unjudgeable=[2], budget=120)])
impl = Task(title="按 `.team/nodes/spec-sol/envcheck-emu/任务书.md` 并行实现严格 preflight 与 owned-emulator measurement 两阶段闸及聚焦测试；只改任务书列明路径，齐后 report_result。", owner_role="impl", seat_wait_seconds=3600, parallel="envcheck-emu-wave", resources=Resources(worktree_id="wt-envcheck-impl", write_paths=["tools/perfbase/envcheck.sh", "tools/perfbase/run-input-ab.sh", "tools/perfbase/test-envcheck-measurement-emulator.sh", ".team/nodes/envcheck-emu/"], read_paths=[".team/nodes/spec-sol/envcheck-emu/任务书.md", ".team/ledgers/acceptance/envcheck-emu.sh", ".team/nodes/input-full-auto/perf-design/CONTRACT.md", "CLAUDE.md", "tools/perfbase/"], **base), handoff=Handoff(required_artifacts=[".team/nodes/envcheck-emu/IMPL.md"]), checks=[Check(id="M.envcheck-emu.impl", script=ScriptRef(path=".team/ledgers/acceptance/envcheck-emu.sh", expect=0, unjudgeable=[2]), cwd=WT, budget=600)])
verify = Task(title="按 `.team/nodes/spec-sol/envcheck-emu/任务书.md` 独立终审 wt-envcheck-impl；重跑机械门并选择所有权/额外 qemu 破坏齿，齐后 report_result。", owner_role="verify", seat_wait_seconds=1800, resources=Resources(worktree_id="wt-envcheck-impl", write_paths=[".team/nodes/envcheck-emu-verify/"], read_paths=[".team/nodes/spec-sol/envcheck-emu/任务书.md", ".team/nodes/envcheck-emu-test/", ".team/nodes/envcheck-emu-probe/", ".team/ledgers/acceptance/envcheck-emu.sh", "tools/perfbase/"], **base), handoff=Handoff(required_artifacts=[".team/nodes/envcheck-emu-verify/VERDICT.md"]), checks=[Check(id="M.envcheck-emu.verify", script=ScriptRef(path=".team/ledgers/acceptance/envcheck-emu.sh", expect=0, unjudgeable=[2]), cwd=WT, budget=600)])
ledger = Ledger(ledger_id="ledger.envcheck-emu.v1", roles=roles, tasks={"t.envcheck-emu.test":test,"t.envcheck-emu.probe":probe,"t.envcheck-emu.impl":impl,"t.envcheck-emu.verify":verify}, dependencies=[dep("t.envcheck-emu.test","t.envcheck-emu.verify"),dep("t.envcheck-emu.probe","t.envcheck-emu.verify"),dep("t.envcheck-emu.impl","t.envcheck-emu.verify")], parallelism=[{"group":"envcheck-emu-wave","max_concurrency":3,"failure_policy":"halt"}], fallback={"F.escalate":FallbackDef(role="advisor",triggers=["blocked_on_unknown","provider_unavailable","result_deadline_elapsed","delivery_uncertain"])}, repo_root="/Volumes/nvme/Projects/远程Agent安卓")
print(ledger.compile(), end="")
