from ledgerdsl import WT, Check, EnvironmentFidelity, FallbackDef, Handoff, Ledger, Provenance, Resources, ScriptRef, Task, dep, role

base = dict(environment_fidelity=EnvironmentFidelity(runs_real_cli=True), provenance=Provenance(identity="git", revision="7bce762bd"))
roles = {
 "test": role(".team/nodes/input-full-auto/sampler-test/", agent="sampler-test-luna2", team="remote-agent-android", provider="codex"),
 "probe": role(".team/nodes/input-full-auto/sampler-probe/", agent="sampler-review-luna2", team="remote-agent-android", provider="codex"),
 "impl": role(".team/nodes/input-full-auto/sampler-impl/", agent="sampler-dev-luna2", team="remote-agent-android", provider="codex"),
 "verify": role(".team/nodes/input-full-auto/sampler-verify/", agent="sampler-review-luna2", team="remote-agent-android", provider="codex"),
 "advisor": role(".team/nodes/input-full-auto/advisor/", agent="input-advisor-luna", team="remote-agent-android", provider="codex"),
}
test = Task(title="按 `.team/nodes/input-full-auto/sampler-test/任务书.md` 并行产出场景红测矩阵；只写本格产物，齐后 report_result。", owner_role="test", seat_wait_seconds=1800, parallel="sampler-wave", resources=Resources(worktree_id="wt-alpha", write_paths=[".team/nodes/input-full-auto/sampler-test/"], read_paths=[".team/nodes/input-full-auto/sampler-test/任务书.md", ".team/nodes/input-full-auto/perf-design/CONTRACT.md", "tools/perfbase/"], **base), handoff=Handoff(required_artifacts=[".team/nodes/input-full-auto/sampler-test/RED.md", ".team/nodes/input-full-auto/sampler-test/cases.json"]), checks=[Check(id="M.sampler.test", script=ScriptRef(path=".team/ledgers/acceptance/sampler-test.sh"), cwd=WT, budget=120)])
probe = Task(title="按 `.team/nodes/input-full-auto/sampler-probe/任务书.md` 并行产出独立根因探针与破坏齿；只写本格产物，齐后 report_result。", owner_role="probe", seat_wait_seconds=1800, parallel="sampler-wave", resources=Resources(worktree_id="wt-bravo", write_paths=[".team/nodes/input-full-auto/sampler-probe/"], read_paths=[".team/nodes/input-full-auto/sampler-probe/任务书.md", ".team/nodes/input-full-auto/perf-design/CONTRACT.md", "tools/perfbase/"], **base), handoff=Handoff(required_artifacts=[".team/nodes/input-full-auto/sampler-probe/PROBE.md"]), checks=[Check(id="M.sampler.probe", script=ScriptRef(path=".team/ledgers/acceptance/sampler-probe.sh"), cwd=WT, budget=120)])
impl = Task(title="按 `.team/nodes/input-full-auto/sampler-impl/任务书.md` 并行实现新 sampler/parser 与 self-test；不得改旧判据或产品码，齐后 report_result。", owner_role="impl", seat_wait_seconds=3600, parallel="sampler-wave", resources=Resources(worktree_id="wt-charlie", write_paths=["tools/perfbase/run-input-ab.sh", "tools/perfbase/parse-input-ab.py", ".team/nodes/input-full-auto/sampler-impl/"], read_paths=[".team/nodes/input-full-auto/sampler-impl/任务书.md", ".team/nodes/input-full-auto/perf-design/CONTRACT.md", "tools/perfbase/"], **base), handoff=Handoff(required_artifacts=[".team/nodes/input-full-auto/sampler-impl/IMPL.md"]), checks=[Check(id="M.sampler.impl", script=ScriptRef(path=".team/ledgers/acceptance/sampler-impl.sh"), cwd=WT, budget=600)])
verify = Task(title="按 `.team/nodes/input-full-auto/sampler-verify/任务书.md` 独立终审 wt-charlie 实现；重跑 self-test 并做破坏齿，齐后 report_result。", owner_role="verify", seat_wait_seconds=1800, resources=Resources(worktree_id="wt-charlie", write_paths=[".team/nodes/input-full-auto/sampler-verify/"], read_paths=[".team/nodes/input-full-auto/sampler-verify/任务书.md", "tools/perfbase/run-input-ab.sh", "tools/perfbase/parse-input-ab.py"], **base), handoff=Handoff(required_artifacts=[".team/nodes/input-full-auto/sampler-verify/VERDICT.md"]), checks=[Check(id="M.sampler.verify", script=ScriptRef(path=".team/ledgers/acceptance/sampler-verify.sh"), cwd=WT, budget=600)])
ledger = Ledger(ledger_id="ledger.perf-sampler.v1", roles=roles, tasks={"t.sampler.test":test,"t.sampler.probe":probe,"t.sampler.impl":impl,"t.sampler.verify":verify}, dependencies=[dep("t.sampler.test","t.sampler.verify"),dep("t.sampler.probe","t.sampler.verify"),dep("t.sampler.impl","t.sampler.verify")], parallelism=[{"group":"sampler-wave","max_concurrency":3,"failure_policy":"halt"}], fallback={"F.escalate":FallbackDef(role="advisor",triggers=["blocked_on_unknown","provider_unavailable","result_deadline_elapsed","delivery_uncertain"])}, repo_root="/Volumes/nvme/Projects/远程Agent安卓")
print(ledger.compile(), end="")
