from ledgerdsl import WT, Check, EnvironmentFidelity, FallbackDef, Handoff, InlineScript, Ledger, Provenance, Resources, ScriptRef, Task, dep, role

base = dict(environment_fidelity=EnvironmentFidelity(runs_real_cli=True), provenance=Provenance(identity="git", revision="c2346f856abf99d25f4e7a1090490cda88525503"))
roles = {
 "test": role(".team/nodes/perf-regress-test/", agent="sampler-test-luna2", team="remote-agent-android", provider="codex"),
 "probe": role(".team/nodes/perf-regress-probe/", agent="sampler-review-luna2", team="remote-agent-android", provider="codex"),
 "impl": role(".team/nodes/perf-regress/", agent="sampler-dev-luna2", team="remote-agent-android", provider="codex"),
 "verify": role(".team/nodes/perf-regress-verify/", agent="sampler-review-luna2", team="remote-agent-android", provider="codex"),
 "advisor": role(".team/nodes/input-full-auto/advisor/", agent="input-advisor-luna", team="remote-agent-android", provider="codex"),
}
test_check = InlineScript(text="f=.team/nodes/perf-regress-test/RED.md\n[ -e \"$f\" ] || exit 1\n[ -r \"$f\" ] || exit 2\n[ -s \"$f\" ] || exit 1\ncommand -v grep >/dev/null 2>&1 || exit 2\ngrep -F PerfRegressionTapRouteBoundaryTest \"$f\" >/dev/null || exit 1\ngrep -F PerfRegressionFirstFrameDrawBoundaryTest \"$f\" >/dev/null || exit 1\ngrep -F PerfRegressionBigScrollbackControlTest \"$f\" >/dev/null || exit 1\ngrep -F -e --rerun-tasks \"$f\" >/dev/null || exit 1\n")
probe_check = InlineScript(text="f=.team/nodes/perf-regress-probe/PROBE.md\n[ -e \"$f\" ] || exit 1\n[ -r \"$f\" ] || exit 2\n[ -s \"$f\" ] || exit 1\ncommand -v grep >/dev/null 2>&1 || exit 2\ngrep -F tap_to_route_enter \"$f\" >/dev/null || exit 1\ngrep -F first_frame_to_first_draw \"$f\" >/dev/null || exit 1\ngrep -F big_scrollback \"$f\" >/dev/null || exit 1\ngrep -F 破坏齿 \"$f\" >/dev/null || exit 1\n")
test = Task(title="按 `.team/nodes/spec-sol/perf-regress/任务书.md` 并行产出性能回归场景红测审计；只写 RED.md，须覆盖 tap→route、frame→draw 与 big_scrollback 阳性对照，齐后 report_result。", owner_role="test", seat_wait_seconds=3600, parallel="perf-regress-wave", resources=Resources(worktree_id="wt-pr-test", write_paths=[".team/nodes/perf-regress-test/"], read_paths=[".team/nodes/spec-sol/perf-regress/任务书.md", ".team/ledgers/acceptance/perf-regress.sh", ".team/nodes/input-full-auto/perf-design/CONTRACT.md", "app/app/src/main/", "app/app/src/test/", "tools/perfbase/"], **base), handoff=Handoff(required_artifacts=[".team/nodes/perf-regress-test/RED.md"]), checks=[Check(id="M.perf-regress.test", script=test_check, cwd=WT, expected=0, unjudgeable=[2], budget=120)])
probe = Task(title="按 `.team/nodes/spec-sol/perf-regress/任务书.md` 并行产出两段操作数归因与因果破坏齿探针；只写 PROBE.md，须覆盖 tap_to_route_enter、first_frame_to_first_draw、big_scrollback，齐后 report_result。", owner_role="probe", seat_wait_seconds=3600, parallel="perf-regress-wave", resources=Resources(worktree_id="wt-pr-probe", write_paths=[".team/nodes/perf-regress-probe/"], read_paths=[".team/nodes/spec-sol/perf-regress/任务书.md", ".team/ledgers/acceptance/perf-regress.sh", ".team/nodes/input-full-auto/perf-design/CONTRACT.md", ".team/nodes/ux4-draw/说明.md", "app/app/src/main/", "app/app/src/test/", "tools/perfbase/"], **base), handoff=Handoff(required_artifacts=[".team/nodes/perf-regress-probe/PROBE.md"]), checks=[Check(id="M.perf-regress.probe", script=probe_check, cwd=WT, expected=0, unjudgeable=[2], budget=120)])
impl = Task(title="按 `.team/nodes/spec-sol/perf-regress/任务书.md` 并行完成 r13 三红格可证伪归因、最小 Android 壳修复、无缓存聚焦测试与新 md5 候选 fresh A/B/A/B；不得调 1.10 或重跑旧 B 抽绿，齐后 report_result。", owner_role="impl", seat_wait_seconds=10800, parallel="perf-regress-wave", resources=Resources(worktree_id="wt-pr-impl", write_paths=["app/app/src/main/java/dev/agentmirror/app/MainNavState.kt", "app/app/src/main/java/dev/agentmirror/app/session/", "app/app/src/main/java/dev/agentmirror/app/termview/", "app/app/src/main/java/dev/agentmirror/app/perf/", "app/app/src/test/", "tools/perfbase/test-perf-regress-attribution.sh", ".team/nodes/perf-regress/"], read_paths=[".team/nodes/spec-sol/perf-regress/任务书.md", ".team/ledgers/acceptance/perf-regress.sh", ".team/nodes/input-full-auto/perf-design/CONTRACT.md", ".team/nodes/ux4-draw/说明.md", ".worktrees/wt-input-perf/.team/nodes/input-full-auto/perf-measure/", "CLAUDE.md", "tools/perfbase/", "app/app/"], **base), handoff=Handoff(required_artifacts=[".team/nodes/perf-regress/ATTRIBUTION.md", ".team/nodes/perf-regress/IMPL.md", ".team/nodes/perf-regress/FIXED-MEASURE.md", ".team/nodes/perf-regress/perf-ab-fixed.json"]), checks=[Check(id="M.perf-regress.impl", script=ScriptRef(path=".team/ledgers/acceptance/perf-regress.sh", expect=0, unjudgeable=[2]), cwd=WT, budget=1200)])
verify = Task(title="按 `.team/nodes/spec-sol/perf-regress/任务书.md` 独立终审 wt-pr-impl；重跑机械门、复算 nearest-rank 三夹具四段并选择唯一因果破坏齿，齐后 report_result。", owner_role="verify", seat_wait_seconds=3600, resources=Resources(worktree_id="wt-pr-impl", write_paths=[".team/nodes/perf-regress-verify/"], read_paths=[".team/nodes/spec-sol/perf-regress/任务书.md", ".team/nodes/perf-regress-test/", ".team/nodes/perf-regress-probe/", ".team/nodes/perf-regress/", ".team/ledgers/acceptance/perf-regress.sh", ".team/nodes/input-full-auto/perf-design/CONTRACT.md", "app/app/", "tools/perfbase/"], **base), handoff=Handoff(required_artifacts=[".team/nodes/perf-regress-verify/VERDICT.md"]), checks=[Check(id="M.perf-regress.verify", script=ScriptRef(path=".team/ledgers/acceptance/perf-regress.sh", expect=0, unjudgeable=[2]), cwd=WT, budget=1200)])
ledger = Ledger(ledger_id="ledger.perf-regress.v1", roles=roles, tasks={"t.perf-regress.test":test,"t.perf-regress.probe":probe,"t.perf-regress.impl":impl,"t.perf-regress.verify":verify}, dependencies=[dep("t.perf-regress.test","t.perf-regress.verify"),dep("t.perf-regress.probe","t.perf-regress.verify"),dep("t.perf-regress.impl","t.perf-regress.verify")], parallelism=[{"group":"perf-regress-wave","max_concurrency":3,"failure_policy":"halt"}], fallback={"F.escalate":FallbackDef(role="advisor",triggers=["blocked_on_unknown","provider_unavailable","result_deadline_elapsed","delivery_uncertain"])}, repo_root="/Volumes/nvme/Projects/远程Agent安卓")
print(ledger.compile(), end="")
