from ledgerdsl import WT, Check, EnvironmentFidelity, FallbackDef, Handoff, Ledger, Provenance, Resources, ScriptRef, Task, dep, role

base = dict(environment_fidelity=EnvironmentFidelity(runs_real_cli=True), provenance=Provenance(identity="git", revision="3668beb1b625381ca5b26026b33a2aa9d8270628"))
roles = {
 "test": role(".team/nodes/scan-filter-test/", agent="sampler-test-luna2", team="remote-agent-android", provider="codex"),
 "probe": role(".team/nodes/scan-filter-probe/", agent="sampler-review-luna2", team="remote-agent-android", provider="codex"),
 "impl": role(".team/nodes/scan-filter-impl/", agent="sampler-dev-luna2", team="remote-agent-android", provider="codex"),
 "verify": role(".team/nodes/scan-filter-verify/", agent="sampler-review-luna2", team="remote-agent-android", provider="codex"),
 "advisor": role(".team/nodes/input-full-auto/advisor/", agent="input-advisor-luna", team="remote-agent-android", provider="codex"),
}
test = Task(title="按 `.team/nodes/spec-sol/scan-filter/任务书.md` 并行产出场景红测审计；只写本格产物，齐后 report_result。", owner_role="test", seat_wait_seconds=1800, parallel="scan-filter-wave", resources=Resources(worktree_id="wt-scan-test", write_paths=[".team/nodes/scan-filter-test/"], read_paths=[".team/nodes/spec-sol/scan-filter/任务书.md", ".team/ledgers/acceptance/scan-filter.sh", "server/internal/discovery/"], **base), handoff=Handoff(required_artifacts=[".team/nodes/scan-filter-test/RED.md"]))
probe = Task(title="按 `.team/nodes/spec-sol/scan-filter/任务书.md` 并行产出分类边界根因探针；只写本格产物，齐后 report_result。", owner_role="probe", seat_wait_seconds=1800, parallel="scan-filter-wave", resources=Resources(worktree_id="wt-scan-probe", write_paths=[".team/nodes/scan-filter-probe/"], read_paths=[".team/nodes/spec-sol/scan-filter/任务书.md", ".team/ledgers/acceptance/scan-filter.sh", "server/internal/discovery/"], **base), handoff=Handoff(required_artifacts=[".team/nodes/scan-filter-probe/PROBE.md"]))
impl = Task(title="按 `.team/nodes/spec-sol/scan-filter/任务书.md` 并行实现 tmux socket fork 前过滤与聚焦测试；只改任务书列明路径，齐后 report_result。", owner_role="impl", seat_wait_seconds=3600, parallel="scan-filter-wave", resources=Resources(worktree_id="wt-scan-impl", write_paths=["server/internal/discovery/scan.go", "server/internal/discovery/scan_filter_test.go", "server/internal/discovery/scan_test.go", "server/internal/discovery/doc.go", ".team/nodes/scan-filter-impl/"], read_paths=[".team/nodes/spec-sol/scan-filter/任务书.md", ".team/ledgers/acceptance/scan-filter.sh", "CLAUDE.md", "server/internal/discovery/"], **base), handoff=Handoff(required_artifacts=[".team/nodes/scan-filter-impl/IMPL.md"]), checks=[Check(id="M.scan-filter.impl", script=ScriptRef(path=".team/ledgers/acceptance/scan-filter.sh", expect=0, unjudgeable=[2]), cwd=WT, budget=600)])
verify = Task(title="按 `.team/nodes/spec-sol/scan-filter/任务书.md` 独立终审 wt-scan-impl；重跑机械门并选择破坏齿，齐后 report_result。", owner_role="verify", seat_wait_seconds=1800, resources=Resources(worktree_id="wt-scan-impl", write_paths=[".team/nodes/scan-filter-verify/"], read_paths=[".team/nodes/spec-sol/scan-filter/任务书.md", ".team/nodes/scan-filter-test/", ".team/nodes/scan-filter-probe/", ".team/ledgers/acceptance/scan-filter.sh", "server/internal/discovery/"], **base), handoff=Handoff(required_artifacts=[".team/nodes/scan-filter-verify/VERDICT.md"]), checks=[Check(id="M.scan-filter.verify", script=ScriptRef(path=".team/ledgers/acceptance/scan-filter.sh", expect=0, unjudgeable=[2]), cwd=WT, budget=600)])
ledger = Ledger(ledger_id="ledger.scan-filter.v1", roles=roles, tasks={"t.scan.test":test,"t.scan.probe":probe,"t.scan.impl":impl,"t.scan.verify":verify}, dependencies=[dep("t.scan.test","t.scan.verify"),dep("t.scan.probe","t.scan.verify"),dep("t.scan.impl","t.scan.verify")], parallelism=[{"group":"scan-filter-wave","max_concurrency":3,"failure_policy":"halt"}], fallback={"F.escalate":FallbackDef(role="advisor",triggers=["blocked_on_unknown","provider_unavailable","result_deadline_elapsed","delivery_uncertain"])}, repo_root="/Volumes/nvme/Projects/远程Agent安卓")
print(ledger.compile(), end="")
