/*
 * Copyright 2026 AgentMirror Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.agentmirror.app.conversation

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Fixtures are the Go worker's projection of a real Pi 1.0.0 RPC turn (gpt-6.1-sol, bash tool),
 * regenerated by server/internal/guirpc TestWriteClientGoldens.
 */
class ConversationStateTest {

    private fun records(name: String): List<Triple<Long, Long, JsonObject>> =
        javaClass.getResource("/conversation/$name")!!.readText().lines().filter { it.isNotBlank() }.map { line ->
            val record = Json.parseToJsonElement(line).jsonObject
            Triple(record["seq"]!!.jsonPrimitive.long, record["ts"]!!.jsonPrimitive.long, record["event"]!!.jsonObject)
        }

    private fun reduceAll(name: String, start: ConversationState = ConversationState()) =
        records(name).fold(start) { state, (seq, ts, event) -> state.apply(seq, ts, event) }

    @Test
    fun realPiTurnReducesToUserToolAndAnswer() {
        val state = reduceAll("pi-tool-turn.live.jsonl")
        val items = state.items
        assertEquals(listOf(UserTurn::class, ToolCall::class, AssistantText::class), items.map { it::class })
        val tool = items[1] as ToolCall
        assertEquals("bash", tool.name)
        assertEquals(ToolPhase.Succeeded, tool.phase)
        assertEquals(0, tool.exitCode)
        assertEquals("echo corral-wire-probe && ls -1 | head -3", tool.arguments!!["command"]!!.jsonPrimitive.content)
        assertTrue(tool.output.startsWith("corral-wire-probe\n"))
        assertTrue(tool.endedAt!! >= tool.startedAt)
        val answer = items[2] as AssistantText
        assertEquals("The probe ran successfully and listed cmds.jsonl, err.txt, and out.jsonl.", answer.text)
        assertFalse(answer.streaming)
        assertFalse(state.running)
    }

    @Test
    fun compactedReplayReducesToTheSameTranscriptAsLive() {
        val live = reduceAll("pi-tool-turn.live.jsonl")
        val replay = reduceAll("pi-tool-turn.replay.jsonl")
        assertEquals(live.items, replay.items)
        assertEquals(live.running, replay.running)
    }

    @Test
    fun replayOverlappingLiveIsIdempotent() {
        val live = reduceAll("pi-tool-turn.live.jsonl")
        val again = records("pi-tool-turn.live.jsonl").fold(live) { s, (seq, ts, e) -> s.apply(seq, ts, e) }
        assertEquals(live, again)
    }

    @Test
    fun streamingTokensGrowOneItemWithStableKey() {
        val all = records("pi-tool-turn.live.jsonl")
        val firstDelta = all.indexOfFirst { it.third["assistantMessageEvent"]?.jsonObject?.get("type")?.jsonPrimitive?.content == "text_delta" }
        var state = all.take(firstDelta).fold(ConversationState()) { s, (seq, ts, e) -> s.apply(seq, ts, e) }
        state = state.apply(all[firstDelta].first, all[firstDelta].second, all[firstDelta].third)
        val streaming = state.items.last() as AssistantText
        assertTrue(streaming.streaming)
        assertEquals("The", streaming.text)
        val after = state.apply(all[firstDelta + 1].first, all[firstDelta + 1].second, all[firstDelta + 1].third)
        assertEquals(streaming.key, after.items.last().key)
        assertEquals("The probe", (after.items.last() as AssistantText).text)
        assertTrue("other items are reused, not copied", state.items.dropLast(1).zip(after.items.dropLast(1)).all { (a, b) -> a === b })
    }

    @Test
    fun localEchoIsReplacedByDeliveredMessageAndDroppedWhenHandled() {
        var state = ConversationState().withLocalEcho("c1", "hello", 0, 1)
        assertEquals(Delivery.Sending, (state.items.single() as UserTurn).delivery)
        state = state.apply(0, 0, event("""{"id":"c1","type":"response","command":"prompt","success":true,"data":{"disposition":"queued"}}"""))
        assertEquals(Delivery.Queued, (state.items.single() as UserTurn).delivery)
        state = state.apply(5, 2, event("""{"type":"message_start","message":{"role":"user","content":"hello","timestamp":2}}"""))
        val delivered = state.items.single() as UserTurn
        assertEquals("m5", delivered.key)
        assertEquals(Delivery.Delivered, delivered.delivery)

        val handled = ConversationState().withLocalEcho("c2", "/codex-compact", 0, 1)
            .apply(0, 0, event("""{"id":"c2","type":"response","command":"prompt","success":true,"data":{"disposition":"handled"}}"""))
        assertTrue(handled.items.isEmpty())
        val rejected = ConversationState().withLocalEcho("c3", "x", 0, 1)
            .apply(0, 0, event("""{"id":"c3","type":"response","command":"prompt","success":false,"error":"busy"}"""))
        assertTrue(rejected.items.isEmpty())
    }

    @Test
    fun settleInterruptsUnfinishedToolsAndAbortIsVisible() {
        var state = ConversationState()
            .apply(1, 10, event("""{"type":"agent_start"}"""))
            .apply(2, 11, event("""{"type":"message_start","message":{"role":"assistant","content":[],"stopReason":"pending","timestamp":3}}"""))
            .apply(3, 12, event("""{"type":"message_update","assistantMessageEvent":{"type":"thinking_start","contentIndex":0}}"""))
            .apply(4, 13, event("""{"type":"message_update","assistantMessageEvent":{"type":"thinking_delta","contentIndex":0,"delta":"Plan"}}"""))
            .apply(5, 20, event("""{"type":"message_update","assistantMessageEvent":{"type":"toolcall_start","contentIndex":1,"id":"t1","toolName":"read"}}"""))
            .apply(6, 21, event("""{"type":"message_update","assistantMessageEvent":{"type":"toolcall_delta","contentIndex":1,"delta":"{\"path\":"}}"""))
        val reasoning = state.items[0] as Reasoning
        assertEquals(20L, reasoning.endedAt)
        assertEquals("{\"path\":", (state.items[1] as ToolCall).argumentsDraft)
        assertTrue(state.quietlyWorking.not())
        state = state
            .apply(7, 30, event("""{"type":"message_end","message":{"role":"assistant","content":[{"type":"thinking","thinking":"Plan it"}],"stopReason":"aborted","timestamp":3}}"""))
            .apply(8, 31, event("""{"type":"agent_settled"}"""))
        assertEquals("Plan it", (state.items[0] as Reasoning).text)
        assertEquals(ToolPhase.Interrupted, (state.items[1] as ToolCall).phase)
        assertEquals("已停止", (state.items.last() as Notice).title)
        assertFalse(state.running)
    }

    @Test
    fun resetKeepsOnlyUndeliveredEchoes() {
        val state = reduceAll("pi-tool-turn.live.jsonl").withLocalEcho("c9", "next", 0, 1).reset("s2", truncated = true)
        assertEquals(listOf("local:c9"), state.items.map { it.key })
        assertEquals("s2", state.stream)
        assertEquals(0L, state.lastSeq)
        assertTrue(state.historyTruncated)
    }

    private fun event(json: String) = Json.parseToJsonElement(json).jsonObject
}
