{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.agentmirror.core",
    "module": "core-terminal",
    "version": "20260914.032773d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-terminal-20260914.032773d.jar",
          "url": "core-terminal-20260914.032773d.jar",
          "size": 59036,
          "sha512": "0b6d0a391070e15cc11cb1e3c480a4c45f4999fb322afba97f81d746c418cdb1b7ba04f86d3d407b3f5e7d630021ad4c65b8c7ce201dcc1950baf099832d1345",
          "sha256": "d674078606f5e960e7380ea2aac628c78a6ef61b18fdd78737f1a0b7b3e65e62",
          "sha1": "d82621b763039b46db9bad342c39cb1c0f035390",
          "md5": "0dbe893cc69f7ddfefbb0581b299728f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-terminal-20260914.032773d.jar",
          "url": "core-terminal-20260914.032773d.jar",
          "size": 59036,
          "sha512": "0b6d0a391070e15cc11cb1e3c480a4c45f4999fb322afba97f81d746c418cdb1b7ba04f86d3d407b3f5e7d630021ad4c65b8c7ce201dcc1950baf099832d1345",
          "sha256": "d674078606f5e960e7380ea2aac628c78a6ef61b18fdd78737f1a0b7b3e65e62",
          "sha1": "d82621b763039b46db9bad342c39cb1c0f035390",
          "md5": "0dbe893cc69f7ddfefbb0581b299728f"
        }
      ]
    }
  ]
}
